#pragma once

#include "NativeGameplayTags.h"

// 项目统一的原生 Gameplay Tag 声明；定义在 SCLGameplayTags.cpp。
// State 描述角色状态，Ability 选择技能，Data 用于 SetByCaller 数值。
namespace SCLGameplayTags
{
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parrying);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ParryAction);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invincible);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Executable);

	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Heavy);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Parry);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Execution);

	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Parry);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Execution);

	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Stamina);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Poise);
	SOULCOMBATLAB_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Guard);
}
